apiVersion: 1

datasources:
  - name: Network Monitor MySQL
    type: mysql
    uid: network_monitor_mysql
    access: proxy
    url: mysql:3306
    database: network_monitor
    user: root
    secureJsonData:
      password: unknown
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true
